test :
	cc *.c ../libft/libft.a ../mlx_2/libmlx.a -framework OpenGL -framework AppKit
	./a.out ./test_maps/42.fdf
	rm -rf ./a.out

test2:
	cc *.c ../libft/libft.a
	./a.out ./test_maps/10-2.fdf
	rm -rf ./a.out

test3:
	cc *.c ../libft/libft.a ../mlx_2/libmlx.a -framework OpenGL -framework AppKit
